name: GitHub Actions Demo

on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: '1 * * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
jobs: 
  build-job: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Task from excerecise
        uses: actions/checkout@v4
      - run: | 
          echo "Name of job is {{ github.event_name }} "
          echo "Branch name {{ github.branch_name  }} "
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
       
  testing-job:
    runs-on: ubuntu-latest
    needs: build-job
    environment: Test
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: testing-job
      - run: | 
          echo "Testing"
  load-test-job:
    runs-on: ubuntu-latest
    needs: build-job
    environment: Load-Test
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: load-test-job
      - run: | 
          echo "Testing"
          sleep 15
  production-job:
    runs-on: ubuntu-latest
    needs: [testing-job, load-test-job]
    environment: 
      name: Production
      url: https://writeabout.net
    if: github.event.input.environment == 'Production'
    steps:
      - name: production-job
      - run: | 
          echo "Step 1 deploying..."
          sleep 10
      - run: | 
          echo "Step 2 deploying..."
          sleep 10
          
