name: GitHub Actions Demo

on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: "15 4 * * SUN"
  workflow_dispatch:

jobs: 
  myjob:
    runs-on: ubuntu-latest 
    steps: 
      - run: |
        echo "Name of job is {{ github.event_name }}"
        echo "List files"
          
  
      
    
