name: GitHub Actions Demo

on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: "15 4 * * SUN"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
jobs: 
  build-job: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4          
      - name: Task from excerecise
      - run: | 
          echo "Name of job is {{ github.event_name }} "
          echo "List files {{ github.branch_name  }} "
  
  testing-job:
    runs-on: ubuntu-latest
    needs: build-job
    environment: Test
    steps:
      - name: testing-job
      - run: | 
          echo "Testing"
  load-test-job:
    runs-on: ubuntu-latest
    needs: build-job
    environment: Load-Test
    steps:
      - name: load-test-job
      - run: | 
          echo "Testing"
          sleep 15
      
          
