name: GitHub Actions Demo

on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: "15 4 * * SUN"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
jobs: 
  myjob: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4          
      - name: Task from excerecise
      - run: | 
          echo "Name of job is {{ github.event_name }} "
          echo "List files {{ github.branch_name  }} "
          
